### ISSUE TITLE
modrinth support?

### ISSUE THREAD

**Issue by nixietab** [sammko/picomc#39] opened 2024-04-23 00:42 UTC
modrinth support would be nice, it has a well documented api and it would be cool to have the possibility to install texturepacks, modpacks, mods, shaders, etc all from the picomc cli

**Comment by sammko** [comment] 2024-04-23 07:27
I think instead I will remove modpack support from picomc altogether, it has been falling apart slowly (e.g. FTB no longer works and I don't have high hopes for curse). While modrinth promises a friendly API and no reverse-engineering of absurd systems designed to prevent anyone from installing the modpack, I think this is better left to specialised tools (such as https://github.com/gorilla-devs/ferium). Integrating ferium with picomc is quite easy, you just point it at the instance directory.

Mod Loader installation on the other hand (fabric, forge) is difficult to emulate without bulit-in picomc support, so I will try to keep that at least somewhat alive.

Also this is a duplicate of #27.

**Closed as not planned by sammko** 2024-04-23 07:27 UTC

**Comment by nixietab** [comment] 2024-04-23 09:45
thanks for the response
